# Generated by Django 3.2.3 on 2021-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.FloatField(blank=True, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
