# Generated by Django 3.2.3 on 2021-05-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
