# Generated by Django 3.1.7 on 2021-05-28 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210528_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_mode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
