# Generated by Django 3.1.7 on 2021-05-28 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auto_20210528_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_by', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
