# Generated by Django 3.1.7 on 2021-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_order_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='otp',
        ),
        migrations.AddField(
            model_name='info',
            name='otp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
